// Generated by CoffeeScript 1.3.3
var addData, conceptSelector, getConcept, parseConcept;

$(document).ready(function() {
  return conceptSelector();
});

conceptSelector = function() {
  return $.ajax({
    type: "GET",
    url: "http://wako3.u-aizu.ac.jp:8080/service/adl/",
    dataType: "json",
    success: function(json) {
      var k, v, _ref;
      _ref = json.adl;
      for (k in _ref) {
        v = _ref[k];
        $("#concept").append($("<option>").val(v).text(v));
      }
      return $("#concept").change(function() {
        return getConcept($("#concept").val());
      });
    }
  });
};

getConcept = function(name) {
  return $.ajax({
    type: "GET",
    url: "http://wako3.u-aizu.ac.jp:8080/service/concept/" + name,
    dataType: "json",
    success: function(json) {
      return parseConcept(json);
    }
  });
};

parseConcept = function(json) {
  var k, parseAdl, parseData, submit, v;
  parseAdl = function(key, json) {
    var k, name, v, _results;
    key = key.replace(/\./g, "___");
    name = "undefined";
    _results = [];
    for (k in json) {
      v = json[k];
      if (k === "name") {
        name = v;
        $("#insert").append("<br />");
        $("#insert").append("<h3>" + name + "</h3>");
        _results.push($("#insert").append($("<table>").attr("id", "" + key).attr("class", "adl")));
      } else {
        $("#" + key).append("<tr><th colspan=\"2\">" + k + "</th></tr>");
        _results.push(parseData(key, v));
      }
    }
    return _results;
  };
  parseData = function(name, array) {
    var c, concept, x, _i, _len, _results;
    concept = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = array.length; _i < _len; _i++) {
        x = array[_i];
        _results.push(conceptBuilder(x));
      }
      return _results;
    })();
    _results = [];
    for (_i = 0, _len = concept.length; _i < _len; _i++) {
      c = concept[_i];
      _results.push($("#" + name).append(c.getHtml()));
    }
    return _results;
  };
  $("#insert").append("<br />").append("<h3>Basic Data</h3>");
  $("#insert").append($("<table>").attr("class", "adl2").append("<tr><td>Patient Name</td><td><input type=\"text\" name=\"pname\" class=\"obj\" /></td></tr>"));
  for (k in json) {
    v = json[k];
    parseAdl(k, v);
  }
  submit = $("<input>").attr("type", "submit").attr("value", "add data");
  $("#insert").append($("<h4>").append(submit));
  return submit.click(function() {
    return addData();
  });
};

addData = function() {
  var i, id, input, json, path, pname, t, table, val, validate, _i, _j, _len, _len1;
  validate = function(data) {
    var val;
    val = data.val();
    if (data.attr("min") != null) {
      if (parseInt(val) < parseInt(data.attr("min"))) {
        val = data.attr("min");
      }
    }
    if (data.attr("max") != null) {
      if (parseInt(data.attr("max")) < parseInt(val)) {
        val = data.attr("max");
      }
    }
    return val;
  };
  json = {};
  pname = validate($("[name=pname]"));
  json.pname = pname;
  table = $(".adl");
  for (_i = 0, _len = table.length; _i < _len; _i++) {
    t = table[_i];
    id = $(t).attr("id");
    json["" + id] = {};
    input = $(".obj", t);
    for (_j = 0, _len1 = input.length; _j < _len1; _j++) {
      i = input[_j];
      val = validate($(i));
      path = $(i).attr("name");
      json["" + id]["" + path] = val;
    }
  }
  return $.ajax({
    type: "POST",
    url: "http://wako3.u-aizu.ac.jp:8080/service/insert",
    contentType: "text/json",
    data: JSON.stringify(json),
    success: function(res) {
      return alert(res);
    }
  });
};
