// Generated by CoffeeScript 1.3.3
var addValidate, errorWindow, validateDvCount, validateDvDateTime, validateDvQuantity;

$(document).ready(function() {
  $("#fieldDate").AnyTime_picker({
    format: "%Y/%m/%d %H:%i:%s",
    earliest: "1980/01/01 01:00:00",
    latest: new Date()
  });
  return $("input").each(function() {
    return addValidate(this);
  });
});

addValidate = function(obj) {
  var type;
  type = $(obj).attr("aqbe:type");
  if (type === "DvQuantity") {
    return $(obj).change(function() {
      return validateDvQuantity(obj);
    });
  } else if (type === "DvCount") {
    return $(obj).change(function() {
      return validateDvCount(obj);
    });
  } else if (type === "DvDateTime") {
    return $(obj).change(function() {
      return validateDvDateTime(obj);
    });
  }
};

errorWindow = function(obj, text) {
  var span;
  span = $(obj).next("span");
  span.css({
    "color": "#ff0000"
  });
  return span.text(text);
};

validateDvQuantity = function(obj) {
  var max, min, type, value;
  type = $(obj).attr("aqbe:type");
  min = parseFloat($(obj).attr("aqbe:min"));
  max = parseFloat($(obj).attr("aqbe:max"));
  value = parseFloat($(obj).val());
  if (!((min <= value && value <= max))) {
    return errorWindow(obj, "Require => min: " + min + " max: " + max);
  } else {
    return errorWindow(obj, "");
  }
};

validateDvCount = function(obj) {
  var max, min, type, value;
  type = $(obj).attr("aqbe:type");
  min = parseInt($(obj).attr("aqbe:min"));
  max = parseInt($(obj).attr("aqbe:max"));
  value = parseInt($(obj).val());
  if (!((min <= value && value <= max))) {
    return errorWindow(obj, "Require => min: " + min + " max: " + max);
  } else {
    errorWindow(obj, "");
    return $(obj).val(Math.round(value));
  }
};

validateDvDateTime = function(obj) {
  var date;
  date = new Date("" + ($(obj).val()));
  return $(obj).next("input").val(date.getTime());
};
